CREATE DATABASE IF NOT EXISTS jobWishList_db;

USE jobWishList_db;

DROP TABLE IF EXISTS jobs;

CREATE TABLE jobs (
    id INT(10) AUTO_INCREMENT NOT NULL,
    company_name VARCHAR(30) NOT NULL,
    job_title VARCHAR(30) NOT NULL,
    date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY(id)
);